#!/usr/bin/env bash
# Copyright (C) 2022 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
# License: GPLv3 or later. See <http://www.gnu.org/licenses/gpl.html>

# Replace Firefox snap with a DEB packaging from official Mozilla APT repository
# Due to snap containment, some software such as gnome extensions and warsaw
#  do not work with the Snap version
# https://support.mozilla.org/en-US/kb/install-firefox-linux
# https://askubuntu.com/a/1516224
# -----------------------------------------------------------------------------

DESCRIPTION='Firefox DEB package from Mozilla Repository'
ARGS='[LANGUAGE_PACK]'

setuplib=${SETUP_LIB_PATH:-"$(dirname "$(readlink -f "$0")")"/../setuplib}
# shellcheck source=../setuplib
if [[ -r "$setuplib" ]]; then source "$setuplib"; else
	echo "Setup library not found: $setuplib" >&2; exit 1;
fi

# -----------------------------------------------------------------------------

l10n=${1:-${SETUP_FIREFOX_L10N:-}}

# -----------------------------------------------------------------------------

repohost=packages.mozilla.org
repourl=https://${repohost}/apt
keyurl=${repourl}/repo-signing-key.gpg
keyfile=/etc/apt/keyrings/${repohost}.asc
expected=35BAA0B33E9EB396F59CA838C0BA5CE6DC6315A3
repofile=/etc/apt/sources.list.d/mozilla.sources
suite=mozilla
packages=( firefox )
if [[ "$l10n" ]]; then
	packages+=( firefox-l10n-"$l10n" )
fi

# Requirements
install_package wget gpg

message "Download and check Mozilla APT repository signing key from $keyurl to $keyfile"
sudo mkdir -p -m 755 -- "${keyfile%/*}"  # already exists in Ubuntu 24.04
wget -q -O- -- "$keyurl" | sudo tee -- "$keyfile"
fingerprint=$(
	gpg -n -q --import --import-options import-show "$keyfile" |
		awk '/pub/{getline; gsub(/^ +| +$/,""); print}'
)
if ! [[ "$fingerprint" == "$expected" ]]; then
	fatal "Key fingerprint '$fingerprint' does not match expected '${expected}'"
fi

message "Add official Mozilla APT repository as $repofile"
sudo tee "$repofile" <<-EOF
	$(signature)

	# Official Mozilla APT repository for Firefox
	# https://support.mozilla.org/en-US/kb/install-firefox-linux
	# https://askubuntu.com/a/1516224
	Types: deb
	URIs: $repourl
	Suites: $suite
	Components: main
	Signed-By: $(escape "$keyfile")
EOF

message "Pin origin and allow unattended upgrades for firefox DEB packages"
sudo tee /etc/apt/preferences.d/mozilla <<-EOF
	$(signature)

	# See also:
	# https://support.mozilla.org/en-US/kb/install-firefox-linux
	# https://askubuntu.com/a/1516224
	# https://manpages.debian.org/unstable/apt/apt_preferences.5.en.html

	# "Disable" all other packages from this repository by setting the lowest priority
	Package: *
	Pin: origin ${repohost}
	Pin-Priority: 1

	# Pin the Mozilla APT repository for firefox packages
	# So it trumps the firefox DEB from Ubuntu that installs the Snap package
	# Priority > 1000: allow downgrades, allow non-target
	Package: firefox*
	Pin: origin ${repohost}
	Pin-Priority: 1001
EOF
sudo tee /etc/apt/apt.conf.d/51unattended-upgrades-firefox <<-EOF
	$(signature)
	Unattended-Upgrade::Origins-Pattern { "archive=${suite}"; };
EOF

message "Close Firefox"
try killall firefox

if package_installed firefox && { package_version firefox | grep -q snap; }; then
	message "Remove DEB package from Ubuntu's apt repository (Snap wrapper)"
	# Firefox in Ubuntu's apt repository is a wrapper for the snap
	sudo apt purge firefox
fi

if snap list firefox &>/dev/null; then
	message "Remove Firefox Snap"
	sudo snap remove firefox
fi

message "Install Firefox from Mozilla APT Repository"
sudo apt update
install_package "${packages[@]}"

message "Decrease syslog verbosity in rtkit-daemon used by Firefox"
override=/etc/systemd/system/rtkit-daemon.service.d/override.conf
sudo mkdir -p -- "${override%/*}"
sudo tee -- "$override" <<-EOF
	$(signature)

	# Decrease syslog verbosity in rtkit-daemon used by Firefox
	# to avoid it spamming "Supervising X threads of X processes of Y users."
	# https://bbs.archlinux.org/viewtopic.php?id=248893
	[Service]
	LogLevelMax=info
EOF
sudo systemctl daemon-reload
sudo systemctl restart rtkit-daemon.service  # needed to silence active service
