#!/usr/bin/env bash
# Copyright (C) 2024 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
# License: GPLv3 or later. See <http://www.gnu.org/licenses/gpl.html>
# -----------------------------------------------------------------------------

DESCRIPTION='Gnome Shell preferences'
ARGS=''

setuplib=${SETUP_LIB_PATH:-"$(dirname "$(readlink -f "$0")")"/../../setuplib}
# shellcheck source=../../setuplib
if [[ -r "$setuplib" ]]; then source "$setuplib"; else
	echo "Setup library not found: $setuplib" >&2; exit 1;
fi

include gsettings

# -----------------------------------------------------------------------------

# Detach Modal Windows (without Gnome Tweaks)
# https://askubuntu.com/a/193894/11015
gsettings set org.gnome.mutter attach-modal-dialogs false

# - Dark Theme:
#	/org/gnome/desktop/interface/color-scheme: 'prefer-dark'
#	/org/gnome/desktop/interface/gtk-theme 'Yaru-dark'
#	/org/gnome/desktop/interface/icon-theme 'Yaru-dark'
# - Dash
# - User Face: https://superuser.com/a/1863052/68321
# - Guest Account
# - Mine Associations
#	text/plain=org.gnome.gedit.desktop;
#	application/vnd.debian.binary-package=gdebi.desktop;
# - Default Font / Scaling
#	org.gnome.desktop.interface.monospace-font-name (13 if 100%, 12-11 if 125% on Xorg)
# - Xorg vs Wayland
# - Install language packs to make sure en_US.UTF8 locale exists
# - Blank Screen / Lock timeouts

# Bugs:
# - journalctl (harmless) spam of multiple lines similar to this:
#		gnome-shell[]: Window manager warning: Overwriting existing binding of keysym 31 with keysym 31 (keycode a).
#	https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1857392
#	Workaround: https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1857392/comments/13
#		(may lose some features of Ubuntu's Dash-To-Dock, launching using CTRL+SUPER+1..N, etc)
