#!/usr/bin/env bash
# Copyright (C) 2021 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
# License: GPLv3 or later. See <http://www.gnu.org/licenses/gpl.html>
# -----------------------------------------------------------------------------

DESCRIPTION='Grub Multiboot'
ARGS=''

setuplib=${SETUP_LIB_PATH:-"$(dirname "$(readlink -f "$0")")"/../setuplib}
# shellcheck source=../setuplib
if [[ -r "$setuplib" ]]; then source "$setuplib"; else
	echo "Setup library not found: $setuplib" >&2; exit 1;
fi

# -----------------------------------------------------------------------------

confdir=/etc/default/grub.d

message "Remember last boot selection"
conf=${confdir}/remember-last-boot.cfg
if ! [[ -e "$conf" ]]; then
	setup_run sudo tee "$conf" <<-EOF
		$(signature)

		# Remember last boot selection
		GRUB_DEFAULT=saved
		GRUB_SAVEDEFAULT=true
	EOF
fi

message "Decrease timeout to 3 seconds"
conf=${confdir}/set-timeout.cfg
if ! [[ -e "$conf" ]]; then
	setup_run sudo tee "$conf" <<-EOF
		$(signature)

		# Set timeout to 3 seconds
		GRUB_TIMEOUT=3
	EOF
fi

# https://bugs.launchpad.net/ubuntu/+source/memtest86+/+bug/567955
message "Disable Memtest86+ serial console entry"
conf=${confdir}/disable-memtest-serial.cfg
if ! [[ -e "$conf" ]]; then
	setup_run sudo tee "$conf" <<-EOF
		$(signature)

		# Set timeout to 3 seconds
		GRUB_MEMTEST_DISABLE_SERIAL=true
	EOF
fi

message "Update Grub"
setup_run sudo update-grub
