#!/usr/bin/env bash
# Copyright (C) 2021 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
# License: GPLv3 or later. See <http://www.gnu.org/licenses/gpl.html>
# -----------------------------------------------------------------------------

DESCRIPTION='GTK3 Examples, notably Icon Browser and Widget Factory'
ARGS=''

setuplib=${SETUP_LIB_PATH:-"$(dirname "$(readlink -f "$0")")"/../setuplib}
# shellcheck source=../setuplib
if [[ -r "$setuplib" ]]; then source "$setuplib"; else
	echo "Setup library not found: $setuplib" >&2; exit 1;
fi

# -----------------------------------------------------------------------------

install_package gtk-3-examples

app_dir=${DATA_HOME}/applications
mkdir -p -- "$app_dir"
for example in /usr/share/applications/gtk3-*.desktop; do
	dest=$app_dir/${example##*/}
	if [[ -f "$dest" ]] || ! [[ -f "$example" ]]; then continue; fi
	grep -vx 'NoDisplay=true' -- "$example" > "$dest"
done
xdg-desktop-menu forceupdate
