#!/usr/bin/env bash
# Copyright (C) 2022 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
# License: GPLv3 or later. See <http://www.gnu.org/licenses/gpl.html>
# -----------------------------------------------------------------------------

DESCRIPTION='MiniDLNA Server'
ARGS='[MEDIA_DIR] [FRIENDLY_NAME]'

setuplib=${SETUP_LIB_PATH:-"$(dirname "$(readlink -f "$0")")"/../setuplib}
# shellcheck source=../setuplib
if [[ -r "$setuplib" ]]; then source "$setuplib"; else
	echo "Setup library not found: $setuplib" >&2; exit 1;
fi
# -----------------------------------------------------------------------------

install_package minidlna

# Fix "WARNING: Inotify max_user_watches [8192] is low ..."
# https://forum.excito.com/viewtopic.php?t=3592
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=613219

# echo 65536 > /proc/sys/fs/inotify/max_user_watches  # single session
# sysctl fs.inotify.max_user_watches=66536  # ?
# /etc/sysctl	fs.inotify.max_user_watches = 66536  # Permanent


# TODO: Patch config file!
