#!/usr/bin/env bash
# Copyright (C) 2021 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
# License: GPLv3 or later. See <http://www.gnu.org/licenses/gpl.html>
# -----------------------------------------------------------------------------

DESCRIPTION='Nautilus preferences'
ARGS=

setuplib=${SETUP_LIB_PATH:-"$(dirname "$(readlink -f "$0")")"/../setuplib}
# shellcheck source=../setuplib
if [[ -r "$setuplib" ]]; then source "$setuplib"; else
	echo "Setup library not found: $setuplib" >&2; exit 1;
fi

include gsettings

# -----------------------------------------------------------------------------

remove=( "${SETUP_NAUTILUS_REMOVE[@]}")
include=("${SETUP_NAUTILUS_INCLUDE[@]}")

# -----------------------------------------------------------------------------

version=$(nautilus --version | awk '{print $NF}')
gsrootpath=org.gnome.nautilus

# Change settings
gsettings set "$gsrootpath".preferences   default-folder-viewer  'list-view'
gsettings set "$gsrootpath".window-state  maximized               true

gsettings array include "$gsrootpath".list-view  default-visible-columns  s "${remove[@]}"
gsettings array remove  "$gsrootpath".list-view  default-visible-columns  s "${include[@]}"

# Reference:
# default-visible-columns=['name', 'size', 'date_modified', 'starred']
# default-column-order=[
# 	'name',
# 	'size',
# 	'type',                     # General, broad variant of mine_type
# 	'owner',
# 	'group',
# 	'permissions',
# 	'mime_type',
# 	'where',                    # (Original) Location, only shows in 'Trash'
# 	'date_modified',            # Only shows time if < 1 day
# 	'date_modified_with_time',
# 	'date_accessed',
# 	'recency',                  # Only shows in 'Recent Files'
# 	'starred'                   # Added on Ubuntu 20.04 (3.36.3)
# ]

if version_lesser "$version" 3.4.2; then
	# Only up to Ubuntu 12.04, as many features were removed in 3.5 and 3.6.
	# https://askubuntu.com/questions/286430
	# https://askubuntu.com/questions/149890
	gsettings set  "$gsrootpath".preferences   date-format           'iso'
	gsettings set  "$gsrootpath".window-state  start-with-status-bar  true
fi
