#!/usr/bin/env bash
# Copyright (C) 2021 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
# License: GPLv3 or later. See <http://www.gnu.org/licenses/gpl.html>
# -----------------------------------------------------------------------------

DESCRIPTION='PHP FPM (FastCGI Process Manager)'
ARGS='PACKAGE(S)...'

setuplib=${SETUP_LIB_PATH:-"$(dirname "$(readlink -f "$0")")"/../setuplib}
# shellcheck source=../setuplib
if [[ -r "$setuplib" ]]; then source "$setuplib"; else
	echo "Setup library not found: $setuplib" >&2; exit 1;
fi

# -----------------------------------------------------------------------------

# Included by default in Ubuntu:
#	Core
#	date
#	filter
#	hash
#	libxml
#	openssl
#	pcre
#	Reflection
#	session
#	sodium
#	SPL
#	standard
#	zlib
# Suggested by default in seten.template.conf:
#	curl
modules=("$@" "${SETUP_PHP_MODULES[@]}")

# FPM pulls PHP. No php-doc for PHP 7+
# For reference:
#   7.2 in Ubuntu 18.04
#   7.4 in Ubuntu 20.04
#   libapache2-mod-php7.* for non-fpm Apache PHP module
packages=(php-fpm)

# -----------------------------------------------------------------------------

message "Install PHP and selected modules"
# Include the modules for installed database systems
declare -A dbms=(
	[mysql-server  ]=php-mysql    # mysql    MySQL
	[mariadb-server]=php-mysql    # mariadb  MariaDB
	[libpq5        ]=php-pgsql    # psql     PostgreSQL
	[libsqlite3-0  ]=php-sqlite3  # sqlite3  SQLite 3
)
for package in "${!dbms[@]}"; do
	if package_installed "$package"; then
		packages+=(php-"${dbms[$package]#php-}")
	fi
done
install_package "${packages[@]}"

if exists a2enmod; then
	message "Apache2 is installed, enabling PHP-FPM modules and settings"
	sudo a2enmod proxy_fcgi setenvif headers
	sudo a2enconf php*-fpm
	sudo systemctl restart apache2
fi
