#!/usr/bin/env bash
# Copyright (C) 2021 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
# License: GPLv3 or later. See <http://www.gnu.org/licenses/gpl.html>

# TODO: Performance tunning for low-trafic, low-resources server:
# /etc/php/7.4/fpm/pool.d/www.conf
# 	pm = dynamic => ondemand; Do not spawn children at start, kill idle
# 	;pm.process_idle_timeout = 10s; => 600s;  # 10 minutes
# TODO: Consider supporting socket-activation
# https://freedesktop.org/wiki/Software/systemd/DaemonSocketActivation
# But it might have some cons, see this:
# https://www.google.com/search?q=%22changing%22+php-fpm+socket-activated

# -----------------------------------------------------------------------------

DESCRIPTION='PHP FPM (FastCGI Process Manager)'
ARGS='PACKAGE(S)...'

setuplib=${SETUP_LIB_PATH:-"$(dirname "$(readlink -f "$0")")"/../setuplib}
# shellcheck source=../setuplib
if [[ -r "$setuplib" ]]; then source "$setuplib"; else
	echo "Setup library not found: $setuplib" >&2; exit 1;
fi

# -----------------------------------------------------------------------------

# Modules included by default in Ubuntu:
#	Core
#	date
#	filter
#	hash
#	libxml
#	openssl
#	pcre
#	Reflection
#	session
#	sodium
#	SPL
#	standard
#	zlib
# Suggested by default in seten.template.conf:
#	curl

# FPM pulls PHP. No php-doc for PHP 7+
# For reference:
#   7.2 in Ubuntu 18.04
#   7.4 in Ubuntu 20.04
#   8.1 in Ubuntu 22.04
#   libapache2-mod-php for non-fpm Apache PHP module
packages=(php-fpm "${SETUP_PHP_MODULES[@]}" "$@")

# -----------------------------------------------------------------------------

message "Install PHP and selected modules"
# Include the modules for installed database systems
declare -A dbms=(
	[mysql-server  ]=php-mysql    # mysql    MySQL
	[mariadb-server]=php-mysql    # mariadb  MariaDB
	[libpq5        ]=php-pgsql    # psql     PostgreSQL
	[libsqlite3-0  ]=php-sqlite3  # sqlite3  SQLite 3
)
for package in "${!dbms[@]}"; do
	if package_installed "$package"; then
		packages+=("${dbms[$package]}")
	fi
done
install_package "${packages[@]}"

if exists a2enmod; then
	message "Apache2 is installed, enabling PHP-FPM modules and settings"
	sudo a2enmod proxy_fcgi setenvif headers
	sudo a2enconf php*-fpm
	sudo systemctl restart apache2
fi
