#!/usr/bin/env bash
# Copyright (C) 2022 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
# License: GPLv3 or later. See <http://www.gnu.org/licenses/gpl.html>
# -----------------------------------------------------------------------------

DESCRIPTION='UFW rules to enable all LAN traffic'
ARGS='[SUBNET]'

setuplib=${SETUP_LIB_PATH:-"$(dirname "$(readlink -f "$0")")"/../setuplib}
# shellcheck source=../setuplib
if [[ -r "$setuplib" ]]; then source "$setuplib"; else
	echo "Setup library not found: $setuplib" >&2; exit 1;
fi
# -----------------------------------------------------------------------------

subnet=${1:-${SETUP_UFW_LAN_SUBNET:-$(ip route | awk 'NR==2{print $1}')}}

#message "Allow all traffic from $subnet"
#setup_run sudo ufw allow from "$subnet"

# To allow only a single LAN IP to a single destination:
# (to allow spurious cast packets from old router)
# https://askubuntu.com/q/1360434/11015
#message "Allow all traffic to $subnet"
sudo ufw allow from 10.1.1.5 to 224.0.0.1  # from old router
#sudo ufw allow from  0.0.0.0 to 224.0.0.1  # from any IPv4 address


# Should not need below, most likely localhost from multiple network adapters (different IP/subnet)
message "Allow known LAN multicast protocols: mDNS, WS-Discovery, etc"
wds_ipv4=239.255.255.250
wds_ipv6='ff02::c'
setup_run sudo tee /etc/ufw/applications.d/lan-multicast.conf <<-EOF
	$(signature)

	# Should be restricted LAN sources and to destinations ${wds_ipv4} (IPv4) and ${wds_ipv6} (IPv6)
	# sudo ufw allow to '${wds_ipv4}' app 'WS-Discovery'
	# sudo ufw allow to '${wds_ipv6}' app 'WS-Discovery'
	[WS-Discovery]
	title=Web Services Dynamic Discovery (WS-Discovery)
	description=Network discovery protocol used by Windows Vista/7/8 and devices such as Onvif cameras, printers, etc
	ports=3702/udp

	# [mDNS]
	# ...

EOF
setup_run sudo ufw allow to "${wds_ipv4}" app 'WS-Discovery'
setup_run sudo ufw allow to "${wds_ipv6}" app 'WS-Discovery'

# ...
try sudo ufw reload
