#!/usr/bin/env bash
# Copyright (C) 2023 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
# License: GPLv3 or later. See <http://www.gnu.org/licenses/gpl.html>
# -----------------------------------------------------------------------------

DESCRIPTION='Wine from Wine HQ repository'
ARGS=''

setuplib=${SETUP_LIB_PATH:-"$(dirname "$(readlink -f "$0")")"/../setuplib}
# shellcheck source=../setuplib
if [[ -r "$setuplib" ]]; then source "$setuplib"; else
	echo "Setup library not found: $setuplib" >&2; exit 1;
fi

# -----------------------------------------------------------------------------

# https://wiki.winehq.org/Ubuntu

declare -A winehq=(
	[name]="Wine HQ"
	[slug]="winehq" #-${SETUP_CODENAME}"
	[url]="https://dl.winehq.org/wine-builds/ubuntu/"
	[key]="https://dl.winehq.org/wine-builds/winehq.key"
)

# Deprecated way using apt-key / apt-add-repository:
# wget -qO- "${winehq[key]}" | sudo apt-key add -
# sudo apt-add-repository --no-update "${winehq[url]}"

# Official, manual way, leading to similar results. Differences:
# - apt-manage key saves as "gpg" instead of "key" (but uses same winehq-archive slug)
# - apt-manage add adds Architecture and X-Repolib-* fields and comments
# - apt-manage is not using codename for slug, to keep a common key
# sudo mkdir -pm755 /etc/apt/keyrings
# sudo wget -O /etc/apt/keyrings/winehq-archive.key "${winehq[key]}"
# sudo wget -NP /etc/apt/sources.list.d/ "${winehq[url]}"/dists/${SETUP_CODENAME}/winehq-${SETUP_CODENAME}.sources

# TODO: Later versions of apt-manage might have indempotent `add`
sudo apt-manage remove --assume-yes "${winehq[slug]}" >/dev/null 2>&1 || true
sudo apt-manage add --terse --source-code --identifier "${winehq[slug]}" --name "${winehq[name]}" "${winehq[url]}"
sudo apt-manage key --url "${winehq[key]}" -- "${winehq[slug]}"

# TODO: use SETUP_RUN ?
sudo dpkg --add-architecture i386
sudo apt update
sudo apt install --install-recommends winehq-stable
