#!/usr/bin/env bash
# Copyright (C) 2025 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
# License: GPLv3 or later. See <http://www.gnu.org/licenses/gpl.html>
# -----------------------------------------------------------------------------

DESCRIPTION='WireShark'
ARGS=''

setuplib=${SETUP_LIB_PATH:-"$(dirname "$(readlink -f "$0")")"/../setuplib}
# shellcheck source=../setuplib
if [[ -r "$setuplib" ]]; then source "$setuplib"; else
	echo "Setup library not found: $setuplib" >&2; exit 1;
fi
# -----------------------------------------------------------------------------


message "Setup WireShark"
# FIXME
# sudo debconf-set-selections <<< 'wireshark-common	wireshark-common/???	boolean	true'
if package_installed wireshark-common; then
	sudo /usr/sbin/dpkg-reconfigure -u wireshark-common
fi

install_package wireshark

sudo usermod -a -G wireshark "$SETUP_USER"
